# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72bc353fdbcb4e0ca536e73b9e3874ee3760d0b9a6408409074e4e360eb731cf35807ce22821bcf5edca709d7c2e8acba0d5325ef6d3f71a1855476e70e760d7

test:
  secret_key_base: 3306d034ee82684df94eb573eccebae92b65a88786f804734c1b193a48235333ac50b6d654a5e8b9666af8be34a66a3b594d9004fdc8bcfbed455d205460857b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
